spring:
  mvc:
    view:
     prefix : /WEB-INF/jsp/
     suffix : .jsp

  datasource:
    url : jdbc:log4jdbc:mariadb://192.168.1.161:3306/park?autoReconnect=true&characterencoding=UTF-8
    username : root
    password : root
    driver-class-name : net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  
  jpa:
    hibernate:
      ddl-auto: update
    properties:      hibernate:
        format_sql : true
    show-sql: true
logging:
  level:
    org:
      springframework:
        security:
          web : trace
      zerock : debug
