spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id : 868530359006-bgoc8ps0dmtdaj35bb0cdprrisc1jc70.apps.googleusercontent.com
            client-secret : OLnzw1W8yVYmpbLgmL-8kFdI
          scope: profile,email #open id provider로 인식하면 openid provider인 구글과 openidprovider가 아닌 네이버/카카오 등으로 나누어서 OAuth2Service를 만들어야함
#https://doorisopen.github.io/spring/2020/03/03/spring-freelec-springboot-chap5.html#